version: '3'
services:
  mw:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    privileged: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .config/.env

