version: '3'
services:
  core:
    build:
      context: ../
      dockerfile: Dockerfile
    security_opt:
           - seccomp:seccomp.json
    cap_drop:
      - all
    ports:
      - 3000:3000
    privileged: false
